### ISSUE TITLE
Integrated web browser for the documentation

### ISSUE THREAD

**Issue by Nidish96** [calculix/cae#13]
Great package, thanks!
One qualm that I have with the latest version is that the documentation launches up in a different browser. 

While I agree with the design decision of opening the model using cgx, I really liked the "integrated feel" of the previous version(s), especially for the documentation. I click on help and the window just expands with the documentation. Now however, there's some delay with opening it in an external viewer (browser). 

Would it be possible to revert back to the previous design just for this?

**Comment by imirzov** [comment]
Dear Nidish,
Thank you for comment!

To open HTML pages directly in the application, it must have an integrated web browser, which makes distribution package +100 MB heavier. I just don't like it. Nowadays any user has a browser installed on his operating system.

More important is why the documentation opens in a new window, but not in a new tab of the browser. Please, can you describe in detail what happens when you click on button 'Help'? Which OS and web browsers are you using? Does CAE align web browser window after opening the documentation? Post some screenshots.

**Comment by Nidish96** [comment]
Thanks for the response.

I'm on ubuntu 20.04, using firefox as my default browser. I also have google chrome installed on my machine, which I rarely use for specific cases. clicking on help on any documentation defaults to opening google chrome - which really takes quite a while when I don't have any chrome browser open. And also, it doesn't quite align with the keyword window quite like the previous versions. Here's a screenshot:
![image](https://user-images.githubusercontent.com/17080531/90192307-546de380-dd88-11ea-8154-1115684e127f.png)
As you can see, the browser doesn't line up like before. But nice thing is, it becomes active whenever I press on "help" even if it's buried behind other windows.

I can see the issue you raise about package size becoming heavier. But the keyword documentation is mostly just text - so I'd be very happy if you could figure out a lightweight way of doing this.

Also, the web browser documentation persists even beyond my keyword input phase.

**Comment by imirzov** [comment]
Dear Nidish,

I see a few issues:
- documentation should be opened in the default web browser;
- web browser window should be aligned after opening.

Thank you for the report. Will try to fix those bugs in future.

By the way, distributing software as binaries makes lots of problems, so I'm going to release only source code and have already rewritten README.md. From this point of view having an integrated web browser is not a problem. And that's why (maybe) old way of opening the documentation could be returned (as an option).

May be the best solution is to give user a possibility to choose in Settings dialog the way documentation will be shown:
- in integrated web browser,
- in Firefox,
- in Chrome,
- etc.

I will think about it.

**Comment by Nidish96** [comment]
Thank You!

**Comment by imirzov** [comment]
Dear Nidish,

With commits made 16-20.06.2021 I returned back the internal web browser for viewing the documentation.
https://github.com/calculix/cae/commits/master
Enjoy!

**Comment by Nidish96** [comment]
The latest version is great! This is definitely turning out to be the ultimate GUI for calculix! Thank you!
