### ISSUE TITLE
Is there any method to import SURFACE set by *.unv file

### ISSUE THREAD

**Issue by kitech-105** [calculix/cae#21]
Hello, I was trying to import sets of surfaces from Salome using *.unv file, 
but they did not automatically show in CAE.
What did I do wrong?
Or is there any better way to define surface set?
Thank you.
![Salome](https://user-images.githubusercontent.com/84913768/121052105-3e805200-c7e4-11eb-9944-81f60f983df0.jpg)
![CAE](https://user-images.githubusercontent.com/84913768/121052134-46d88d00-c7e4-11eb-8172-3599b23fc9b7.jpg)

**Comment by imirzov** [comment]
Hi! Thanks for the issue.
Please, share your UNV model somehow. I will test the [unv2ccx](https://github.com/calculix/unv2ccx) converter.
As I can see, UNV2467Reader() method of the reader.py distinguishes only node and element sets. So, surfaces are not supported. Can't even imagine, how I admitted such a mistake.

**Comment by imirzov** [comment]
One more remark. In Salome groups mean:

- Group of Nodes = node set
- Group of Faces = set of shell elements
- Group of Volumes = set of solid elements

When you define a Group of Faces in Salome, it does not create surfaces in meaning of CalculiX. Instead, Salome creates shell elements and then exports them into UNV file. That is why UNV file has no information about solid element faces - in surface definition they a replaced by shells.

So this issue is the UNV format issue. It does not support surfaces - only nodes, elements and element sets.
