### ISSUE TITLE
paraview warp by vector

### ISSUE THREAD

**Issue by Nidish96** [calculix/cae#4]
First, thanks a LOT for this package! This is amazing!

I just did a structural modal analysis (*frequency card), and wanted to view the results in paraview. However, on paraview, I'm not able to click on "warp by vector" as it seems to be hidden off.
Let me know if this is some issue with the ccx2paraview conversion or it can be fixed easily.

Here's a zip file with the input (_main.inp is the main file that has to be run) and its output in frd (_main.frd)
[send.zip](https://github.com/calculix/cae/files/4466005/send.zip)

Thanks,
Nidish

**Comment by imirzov** [comment]
Dear Nidish,
Thank you for using this software!

Which version of ccx2paraview are you using? Is it the latest one?
https://github.com/calculix/ccx2paraview/releases/tag/v2.3
I've successfully converted your model with ccx2paraview v2.3. And warp by vector works fine.
So the problem maybe is due to old buggy converter.

![Screenshot from 2020-04-12 10-06-17](https://user-images.githubusercontent.com/4652710/79063953-4eb2a500-7ca5-11ea-8b90-97cba3deffac.png)

You can manually replace CAE's converter in the 'bin' folder.

**Comment by imirzov** [comment]
Please, may I add your model to our examples?
https://github.com/calculix/examples/
